import { db } from "@/server/db";
import { reportShares, reportShareEvents } from "@/server/db/schema";
import { eq } from "drizzle-orm";
import { headers } from "next/headers";
import { getReadUrl } from "@/server/services/storage";
import { Lock, FileText } from "lucide-react";

/**
 * Public report-share landing page — the client's side of send & receipt.
 * No auth: the token IS the credential. Framed as the CONTRACTOR's
 * document (their name and logo); Sitefile appears only as a quiet
 * footer. Every view logs an "opened" event for the receipt timeline.
 */

export const dynamic = "force-dynamic";

export default async function SharePage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const share = await db.query.reportShares.findFirst({
    where: eq(reportShares.token, token),
    with: {
      report: {
        with: {
          project: { with: { organisation: true } },
        },
      },
    },
  });

  if (!share || share.revokedAt || share.report.status !== "completed") {
    return (
      <main className="flex min-h-screen items-center justify-center bg-background p-6">
        <div className="max-w-sm text-center">
          <FileText className="mx-auto mb-3 h-8 w-8 text-muted-foreground" />
          <h1 className="text-lg font-semibold">This link is no longer available</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            The report link may have been withdrawn or replaced. Please
            contact whoever sent it to you for a fresh link.
          </p>
        </div>
      </main>
    );
  }

  const { report } = share;
  const org = report.project.organisation;
  const hasPassword = report.passwordHash != null;
  const logoUrl = org.logoUrl
    ? org.logoUrl.startsWith("http")
      ? org.logoUrl
      : await getReadUrl(org.logoUrl)
    : null;

  // Receipt: log the open (every view; the timeline reports the first).
  const ua = (await headers()).get("user-agent")?.slice(0, 300) ?? null;
  await db.insert(reportShareEvents).values({
    shareId: share.id,
    event: "opened",
    userAgent: ua,
  });

  const period = `${formatDate(report.periodStart)} — ${formatDate(report.periodEnd)}`;

  return (
    <main className="flex min-h-screen items-center justify-center bg-background p-6">
      <div className="w-full max-w-md rounded-xl border bg-card p-8 text-card-foreground shadow-sm">
        <div className="mb-6 text-center">
          {logoUrl ? (
            // eslint-disable-next-line @next/next/no-img-element -- contractor logo
            <img
              src={logoUrl}
              alt={org.name}
              className="mx-auto mb-3 h-12 max-w-40 object-contain"
            />
          ) : (
            <div className="mb-3 text-lg font-bold">{org.name}</div>
          )}
          <div className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
            Progress Report
          </div>
        </div>

        <h1 className="text-center text-xl font-bold">
          {report.project.name}
        </h1>
        <dl className="mx-auto mt-4 max-w-xs space-y-1.5 text-sm">
          <div className="flex justify-between">
            <dt className="text-muted-foreground">Report</dt>
            <dd className="font-medium">№ {report.reportNumber}</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-muted-foreground">Period</dt>
            <dd className="font-medium">{period}</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-muted-foreground">Issued by</dt>
            <dd className="font-medium">{org.name}</dd>
          </div>
        </dl>

        <a
          href={`/api/share/${token}/pdf`}
          className="mt-6 flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground hover:brightness-95"
        >
          <FileText className="h-4 w-4" />
          Download report (PDF)
        </a>

        {hasPassword && (
          <p className="mt-3 flex items-start justify-center gap-1.5 text-center text-xs text-muted-foreground">
            <Lock className="mt-0.5 h-3.5 w-3.5 shrink-0" />
            This PDF is encrypted. The sender will give you the password
            separately.
          </p>
        )}

        <p className="mt-6 border-t pt-4 text-center text-[11px] text-muted-foreground">
          Evidence-backed progress report · Generated by Sitefile
        </p>
      </div>
    </main>
  );
}

function formatDate(iso: string): string {
  return new Date(iso + "T00:00:00").toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}
